# Generated by Django 5.0.6 on 2025-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du film', max_length=255, verbose_name='Titre')),
                ('description', models.TextField(help_text='Synopsis du film', verbose_name='Description')),
                ('image_url', models.URLField(help_text="Lien vers l'affiche du film", verbose_name="URL de l'affiche")),
                ('release_date', models.DateField(help_text='Date de sortie du film', verbose_name='Date de sortie')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Réalisateur')),
                ('actors', models.TextField(blank=True, help_text='Liste des acteurs principaux', null=True, verbose_name='Acteurs')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Genre')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Note du film (ex: 7.5)', max_digits=3, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['-release_date'],
            },
        ),
    ]
